docs: add comments for frrouting configure file
ching-kuo/infra-labs-docs pull request #2
Opened 2022-05-19 07:35 UTC by steveyiyo

2022-05-20 07:15 UTC, ching-kuo commented
@steveyiyo Can you move the PDF file one directory up.
`terrafrom` directory should only include Terraform stuffs
Thanks!

2022-05-20 08:43 UTC, steveyiyo commented
@ching-kuo Did you mean README.md file?

2022-05-20 08:43 UTC, ching-kuo commented
Yes

2022-05-20 08:46 UTC, steveyiyo commented
@ching-kuo done, Could you please check on it?

2022-05-20 11:12 UTC, ching-kuo commented
@steveyiyo Can you add how to run the Terraform script to setup the environment in the README
Please include

- Downloading/setting up OpenStack credential 
- Link to Terraform installation page 
- How to run Terraform script
- How to destroy the environment

Thanks

2022-05-21 12:12 UTC, steveyiyo commented
OK, I will do it ASAP.

2022-05-21 15:51 UTC, steveyiyo commented
@ching-kuo I have pushed the guide about how to run terraform scripts. Once you merged to the master repo, I will open a new PR to split the README.md file.

Thanks!

2022-05-22 09:59 UTC, ching-kuo requested changes
Minor comments

2022-05-22 09:59 UTC, ching-kuo commented on self-paced-labs/network/frr_bgp/README.md
> +export OS_TENANT_NAME="" # 輸入 OpenStack 的帳號
OS_TENANT_NAME is the project name in OpenStack

2022-05-22 09:59 UTC, ching-kuo commented on self-paced-labs/network/frr_bgp/README.md
> +export OS_AUTH_URL="https://openstack.cloudnative.tw:5000" # 輸入 OpenStack 的授權網址，可以在 API Access 中找到
We can download the credential file directly from dashboard, which will be easier in most cases.

2022-05-22 09:59 UTC, ching-kuo commented on self-paced-labs/network/frr_bgp/terraform/00_variables.tf
> +
Prefer not to hard code this, this should be included in the credential file.

2022-05-22 19:09 UTC, steveyiyo commented
@ching-kuo Thanks for the feedback. Please check it again.

2022-05-24 05:54 UTC, ching-kuo reviewed
Minor comment, otherwise LGTM

2022-05-24 05:54 UTC, ching-kuo commented on self-paced-labs/network/frr_bgp/README.md
> +terraform apply -destroy
```terraform destroy``` seems more common

2022-05-25 10:59 UTC, ching-kuo approved these changes

2022-05-25 10:59 UTC, merged